import random


lista_palavras = [
    "avião",
    "banco",
    "bola",
    "cachorro",
    "café",
    "carro",
    "castelo",
    "chave",
    "chuva",
    "cidade",
    "coroa",
    "diamante",
    "dinheiro",
    "dragão",
    "escola",
    "estrela",
    "fantasma",
    "fogo",
    "floresta",
    "gato",
    "gelo",
    "hospital",
    "ilha",
    "janela",
    "jogo",
    "lua",
    "médico",
    "montanha",
    "navio",
    "neve",
    "olho",
    "ouro",
    "papel",
    "parque",
    "peixe",
    "ponte",
    "praia",
    "rei",
    "relógio",
    "robô",
    "sol",
    "telefone",
    "terra",
    "tigre",
    "trem",
    "universidade",
    "vento",
    "viagem",
    "vidro",
    "vulcão"
]


def sortear_palavras(lista_palavras, quantidade):
    return random.sample(lista_palavras, quantidade) # sample =  aleatorio mas sem repetir, diferente de choice() que pode escolher a mesma palavra mais de uma vez