import random

lista_palavras = [
    "AVIÃO",
    "ABELHA",
    "ÁGUA",
    "ALIANÇA",
    "AMIGO",
    "ANJO",
    "ÁRVORE",
    "ASTRONAUTA",
    "BANANA",
    "BANCO",
    "BARCO",
    "BICICLETA",
    "BOLA",
    "BOMBA",
    "BORBOLETA",
    "BRASIL",
    "CAFÉ",
    "CACHORRO",
    "CADEIRA",
    "CAMISA",
    "CARRO",
    "CASA",
    "CELULAR",
    "CHAVE",
    "CHOCOLATE",
    "CHUVA",
    "CIDADE",
    "COMPUTADOR",
    "COROA",
    "DESERTO",
    "DINHEIRO",
    "DRAGÃO",
    "ESCOLA",
    "ESPELHO",
    "ESPAÇO",
    "ESTRELA",
    "FACA",
    "FILME",
    "FOGO",
    "FLORESTA",
    "GATO",
    "GELO",
    "GIGANTE",
    "HOSPITAL",
    "ILHA",
    "JANELA",
    "JARDIM",
    "JOGO",
    "LÁPIS",
    "LIVRO",
    "LUA",
    "MAR",
    "MÁSCARA",
    "MESA",
    "MOEDA",
    "MONTANHA",
    "MÚSICA",
    "NAVIO",
    "NEVE",
    "NUVEM",
    "OLHO",
    "OURO",
    "PAPEL",
    "PÁSSARO",
    "PEDRA",
    "PEIXE",
    "PIRATA",
    "PIZZA",
    "PLANETA",
    "PONTE",
    "PORTA",
    "PRAIA",
    "PRÍNCIPE",
    "QUEIJO",
    "RELÓGIO",
    "RIO",
    "ROBÔ",
    "ROSA",
    "SAPATO",
    "SERPENTE",
    "SOL",
    "SORVETE",
    "TELEFONE",
    "TEMPLO",
    "TIGRE",
    "TORRE",
    "TREM",
    "UNIVERSO",
    "VAMPIRO",
    "VELA",
    "VENTO",
    "VULCÃO",
    "XADREZ",
    "ZEBRA",
    "CASTELO",
    "FANTASMA",
    "FOGUETE",
    "GARFO",
    "MÉDICO",
    "CAVALO"
]

def sortear_palavras(list_pal: list[str], quantidade: int) -> list[str]:
    """Sorteia uma quantidade de palavras aleatórias sem repetição.

    Args:
        list_pal: Uma lista contendo todas as palavras disponíveis para o jogo.
        quantidade: O número de palavras que devem ser sorteadas.

    Returns:
        Uma lista contendo as palavras sorteadas aleatoriamente.
    """
    return random.sample(list_pal, quantidade)